# Generated by Django 5.0 on 2026-09-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='category',
            field=models.CharField(choices=[('activity', 'Activity'), ('music', 'Music'), ('film', 'Film'), ('place', 'Place')], default='activity', max_length=20),
        ),
    ]
